/* ============================================================================
 * estate.js — Brackenford Care Group: the simulated pilot estate.
 * SINGLE SOURCE OF TRUTH for both the dashboard and Cassi's grounding.
 *
 * Full CQC Single Assessment Framework build: all 34 quality statements per
 * home (170 records), generated by merging per-home story overrides onto a
 * plausible baseline, so the data stays internally coherent.
 *
 * Everything here is invented placeholder data. The group name is a single
 * constant below.
 * ========================================================================== */

const GROUP = "Brackenford Care Group";

/* ---- CQC SAF quality statement catalogue (cqc-saf-2024) ------------------ */
const QS_CATALOGUE = [
  // Safe
  { id: "S1", kq: "Safe", title: "Learning culture" },
  { id: "S2", kq: "Safe", title: "Safe systems, pathways and transitions" },
  { id: "S3", kq: "Safe", title: "Safeguarding" },
  { id: "S4", kq: "Safe", title: "Involving people to manage risks" },
  { id: "S5", kq: "Safe", title: "Safe environments" },
  { id: "S6", kq: "Safe", title: "Safe and effective staffing" },
  { id: "S7", kq: "Safe", title: "Infection prevention and control" },
  { id: "S8", kq: "Safe", title: "Medicines optimisation" },
  // Effective
  { id: "E1", kq: "Effective", title: "Assessing needs" },
  { id: "E2", kq: "Effective", title: "Delivering evidence-based care and treatment" },
  { id: "E3", kq: "Effective", title: "How staff, teams and services work together" },
  { id: "E4", kq: "Effective", title: "Supporting people to live healthier lives" },
  { id: "E5", kq: "Effective", title: "Monitoring and improving outcomes" },
  { id: "E6", kq: "Effective", title: "Consent to care and treatment" },
  // Caring
  { id: "C1", kq: "Caring", title: "Kindness, compassion and dignity" },
  { id: "C2", kq: "Caring", title: "Treating people as individuals" },
  { id: "C3", kq: "Caring", title: "Independence, choice and control" },
  { id: "C4", kq: "Caring", title: "Responding to people's immediate needs" },
  { id: "C5", kq: "Caring", title: "Workforce wellbeing and enablement" },
  // Responsive
  { id: "R1", kq: "Responsive", title: "Person-centred care" },
  { id: "R2", kq: "Responsive", title: "Care provision, integration and continuity" },
  { id: "R3", kq: "Responsive", title: "Providing information" },
  { id: "R4", kq: "Responsive", title: "Listening to and involving people" },
  { id: "R5", kq: "Responsive", title: "Equity in access" },
  { id: "R6", kq: "Responsive", title: "Equity in experiences and outcomes" },
  { id: "R7", kq: "Responsive", title: "Planning for the future" },
  // Well-led
  { id: "W1", kq: "Well-led", title: "Shared direction and culture" },
  { id: "W2", kq: "Well-led", title: "Capable, compassionate and inclusive leaders" },
  { id: "W3", kq: "Well-led", title: "Freedom to speak up" },
  { id: "W4", kq: "Well-led", title: "Workforce equality, diversity and inclusion" },
  { id: "W5", kq: "Well-led", title: "Governance, management and sustainability" },
  { id: "W6", kq: "Well-led", title: "Partnerships and communities" },
  { id: "W7", kq: "Well-led", title: "Learning, improvement and innovation" },
  { id: "W8", kq: "Well-led", title: "Environmental sustainability" },
];

/* ---- baseline evidence for a "Good, nothing remarkable" statement -------- */
const BASELINE_EVIDENCE = {
  S1: ["Incident log current; lessons recorded against each closed incident", "Monthly learning review minuted with actions assigned"],
  S2: ["Hospital transfer packs complete on last 4 admissions/discharges", "Pre-admission assessments on file for all residents admitted this year"],
  S3: ["Safeguarding log current; all referrals tracked to outcome", "Staff safeguarding training at or above group target"],
  S4: ["Risk assessments reviewed within the last 8 weeks for all residents", "Positive-risk decisions recorded with resident/family involvement"],
  S5: ["Environment audit completed this quarter; actions closed", "Fire safety checks and equipment servicing in date"],
  S6: ["Rota cover meets dependency tool requirements over the last cycle", "Agency use low; induction records complete for recent starters"],
  S7: ["IPC audit passed this quarter; no outstanding actions", "Outbreak plan current; hand-hygiene observations on file"],
  S8: ["MAR charts complete over the last audit cycle", "Medicines competencies in date for staff who administer"],
  E1: ["Needs assessments current; reviewed on change of need", "Nutrition and hydration assessments in date"],
  E2: ["Care delivered in line with current guidance; policies in date", "Wound care and falls protocols followed in sampled records"],
  E3: ["GP rounds and MDT input recorded weekly", "Handover records complete; community team referrals tracked"],
  E4: ["Healthy-eating and activity plans in place where chosen", "Health-promotion checks (oral care, hearing, sight) tracked"],
  E5: ["Outcome measures tracked monthly and reviewed by the GM", "Falls, weight loss and pressure-care trends reviewed at clinical governance"],
  E6: ["Consent recorded for care plans; MCA assessments where indicated", "DoLS applications tracked; conditions on authorisations met"],
  C1: ["Dignity observations completed; positive relative feedback on file", "No dignity-related complaints in the last quarter"],
  C2: ["Life-history work on file for residents; preferences acted on", "Care plans reflect individual routines and choices"],
  C3: ["Residents supported to maintain independence; aids in place", "Choice recorded at mealtimes, activities, daily routines"],
  C4: ["Call-bell response times within target on last audit", "Changes in need escalated same-day in sampled records"],
  C5: ["Supervision in date; staff survey response stable", "Wellbeing check-ins recorded after difficult events"],
  R1: ["Care plans person-centred and current in sampled records", "Resident and family involvement recorded at reviews"],
  R2: ["Continuity maintained across shifts; keyworker system in place", "External provider input coordinated and recorded"],
  R3: ["Information available in accessible formats on request", "Service guide current; noticeboards and updates maintained"],
  R4: ["Complaints log current; outcomes recorded and shared", "Resident and relative meetings minuted with actions"],
  R5: ["Admissions assessed on need; no inappropriate refusals on file", "Interpreting and advocacy arranged where needed"],
  R6: ["Protected-characteristics needs reflected in care plans", "Outcomes monitored across resident groups; no unexplained variation"],
  R7: ["Advance care plans in place where residents have chosen", "End-of-life wishes recorded and shared with relevant professionals"],
  W1: ["Vision and values displayed and reflected in team meetings", "Staff describe consistent priorities in supervision records"],
  W2: ["Registered manager in post; leadership visible on the floor", "Deputy cover arrangements clear and tested"],
  W3: ["Speak-up route publicised; concerns log shows issues raised and closed", "No unresolved whistleblowing matters"],
  W4: ["EDI training in date; recruitment monitoring in place", "Flexible-working requests considered and recorded"],
  W5: ["Manager audit cycle on schedule; QA log current", "Governance actions tracked to closure; board report submitted monthly"],
  W6: ["Links with GP practice, community teams and local groups active", "Joint working recorded with hospice and pharmacy"],
  W7: ["Improvement projects logged with measurable aims", "Learning from audits feeds the improvement plan"],
  W8: ["Energy and waste monitoring in place", "Sustainability actions included in the maintenance plan"],
};

/* ---- per-home profiles + story overrides ---------------------------------
 * Override shape: { gm, cassi, dir, evidence:[...], gaps:[...] }
 * Anything not overridden = Good/Good, flat, baseline evidence, no gaps.
 * -------------------------------------------------------------------------- */
const HOMES = [
  {
    id: "meadowbrook",
    name: "Meadowbrook House",
    town: "Guildford, Surrey",
    gmName: "Priya Shah",
    rm: "Anne Doyle",
    beds: 48,
    overall: { label: "Good", rag: "green", dir: "up" },
    lastAssessed: "18 May 2026",
    kq: {
      Safe: { gm: "Good", cassi: "Good", dir: "up", note: "Medicines recording gaps from March closed; weekly audits embedded since April." },
      Effective: { gm: "Good", cassi: "Good", dir: "flat", note: "Care plans current; outcomes tracked." },
      Caring: { gm: "Good", cassi: "Good", dir: "flat", note: "Positive relative feedback; dignity observations complete." },
      Responsive: { gm: "Good", cassi: "Good", dir: "up", note: "Activities programme broadened; complaints handled in time." },
      "Well-led": { gm: "Good", cassi: "Good", dir: "up", note: "Audit cycle current; governance log updated monthly." },
    },
    overrides: {
      S8: {
        dir: "up",
        evidence: [
          "Weekly medication audits running since 6 April; last four cycles clean",
          "No missed PRN signatures since 14 April (two missed in March)",
          "MAR completeness 'no exceptions' on the 12 May pharmacy-led audit",
          "Competency reassessment completed for the two staff involved in the March gaps",
        ],
        gaps: [],
        narrative:
          "The March position was Requires improvement: recording gaps and two missed PRN signatures, raised by the GM herself. The May evidence shows the fix embedded, not asserted — audits weekly, signatures clean, competencies redone.",
      },
      S1: {
        evidence: [
          "GM self-reported the March medication recording gaps before audit found them",
          "Learning review on 20 March produced the weekly-audit action now embedded",
          "Lessons summary shared with staff at the April team meeting (minuted)",
        ],
        gaps: [],
      },
      R1: { dir: "up", evidence: ["Activities programme expanded in April after resident feedback", "Care plan reviews all in date; resident voice recorded at each"], gaps: [] },
    },
    history: [
      { date: "12 Mar 2026", text: "Safe (Medicines optimisation, S8) self-rated Requires improvement — recording gaps, two missed PRN signatures, flagged by the GM herself." },
      { date: "18 May 2026", text: "S8 self-rated Good — weekly audits since April, four clean cycles, competencies redone. Cassi's assessment agrees: the evidence holds." },
    ],
    strengths: ["Improvement is evidence-backed, not asserted", "GM raised the March gap herself — strong learning culture"],
    redFlags: [],
  },

  {
    id: "oakfield",
    name: "Oakfield Lodge",
    town: "Stockport, Gtr Manchester",
    gmName: "Mark Ellison",
    rm: "Carol Whitfield",
    beds: 62,
    overall: { label: "Good", rag: "green", dir: "flat" },
    lastAssessed: "20 May 2026",
    kq: {
      Safe: { gm: "Good", cassi: "Good", dir: "flat", note: "Risk assessments current; staffing stable." },
      Effective: { gm: "Good", cassi: "Good", dir: "flat", note: "Training compliance above target." },
      Caring: { gm: "Good", cassi: "Good", dir: "flat", note: "Stable relative feedback." },
      Responsive: { gm: "Good", cassi: "Good", dir: "flat", note: "KQ-level ratings align, but see the QS-level divergence on Listening (R4)." },
      "Well-led": { gm: "Good", cassi: "Requires improvement", dir: "flat", note: "Governance evidence is thin — recorded one level above the evidence." },
    },
    overrides: {
      W5: {
        gm: "Good",
        cassi: "Requires improvement",
        evidence: [
          "Last completed manager audit dated 9 February — none since",
          "Quality-assurance log not updated this quarter",
          "Two governance actions past their due date (call-bell audit, supervision tracker refresh)",
        ],
        gaps: [
          "No completed manager audit for over three months",
          "QA log has no entries for Q2",
          "Overdue actions have no revised dates or owner notes",
        ],
        narrative:
          "The GM recorded Good; the evidence on file supports Requires improvement. This is the estate's clearest exposure — the rating of record sits one level above what the governance evidence can carry.",
      },
      R4: {
        gm: "Good",
        cassi: "Requires improvement",
        evidence: [
          "Complaints log shows three complaints since March without recorded outcome letters",
          "Resident and relative meetings not minuted since 12 March",
        ],
        gaps: ["Outcome letters missing for three complaints", "No minuted resident/relative meeting in over two months"],
        narrative:
          "A QS-level divergence the key-question view doesn't show: Responsive is Good at KQ level on both sides, but on Listening (R4) the GM recorded Good over evidence that supports Requires improvement.",
      },
      W7: { evidence: ["Improvement plan exists but last reviewed in February", "Audit-to-action link weak in Q2 — few audits completed to learn from"], gaps: ["Improvement plan review overdue"] },
    },
    history: [
      { date: "20 May 2026", text: "Well-led (Governance, W5) recorded Good; Cassi assessed Requires improvement — recorded ABOVE assessment. A second QS-level divergence on Listening (R4) sits beneath an aligned Responsive rating." },
    ],
    strengths: ["Four of five key questions carry sound evidence", "Care-facing statements (Safe, Caring) are genuinely solid"],
    redFlags: ["No completed manager audit since 9 February", "QA log empty for Q2", "Three complaints without recorded outcomes"],
  },

  {
    id: "riverside",
    name: "Riverside Court",
    town: "Leeds, West Yorkshire",
    gmName: "Sandra Beale",
    rm: "Tom Hargreaves",
    beds: 40,
    overall: { label: "Good", rag: "green", dir: "flat" },
    lastAssessed: "15 May 2026",
    kq: {
      Safe: { gm: "Good", cassi: "Good", dir: "flat", note: "Complete and current." },
      Effective: { gm: "Good", cassi: "Good", dir: "flat", note: "Strong outcome tracking." },
      Caring: { gm: "Good", cassi: "Good", dir: "flat", note: "Consistent positive feedback." },
      Responsive: { gm: "Good", cassi: "Good", dir: "up", note: "Care-plan reviews timely; person-centred work strong." },
      "Well-led": { gm: "Good", cassi: "Good", dir: "flat", note: "Governance current; audits on schedule." },
    },
    overrides: {
      R1: {
        dir: "up",
        evidence: [
          "Sampled care plans show resident voice in the resident's own words",
          "Keyworker reviews monthly, with family contributions recorded",
          "‘This is me' profiles complete for all residents",
        ],
        gaps: [],
      },
      E5: { evidence: ["Falls down two quarters running; analysis on file links it to the sensor-mat rollout", "Outcome dashboard reviewed at monthly clinical governance"], gaps: [] },
    },
    history: [
      { date: "15 May 2026", text: "Consistent Good across all 34 quality statements. No divergence anywhere between the rating of record and Cassi's assessment — the estate's healthy baseline." },
    ],
    strengths: ["Complete, current evidence base", "No divergence — what aligned looks like"],
    redFlags: [],
  },

  {
    id: "thornbury",
    name: "Thornbury Manor",
    town: "Bristol",
    gmName: "Daniel Okafor",
    rm: "Lisa Penrose",
    beds: 55,
    overall: { label: "Requires improvement", rag: "amber", dir: "down" },
    lastAssessed: "16 May 2026",
    kq: {
      Safe: { gm: "Good", cassi: "Good", dir: "flat", note: "Holding." },
      Effective: { gm: "Good", cassi: "Good", dir: "flat", note: "Stable." },
      Caring: { gm: "Requires improvement", cassi: "Requires improvement", dir: "down", note: "Honest downgrade by the GM — complaints up, dignity concerns, turnover biting." },
      Responsive: { gm: "Good", cassi: "Good", dir: "flat", note: "In time." },
      "Well-led": { gm: "Good", cassi: "Good", dir: "flat", note: "Governance current; the GM's own reporting surfaced the Caring decline." },
    },
    overrides: {
      C1: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        dir: "down",
        evidence: [
          "Two relatives raised dignity concerns in April (personal care rushed at morning peak)",
          "Complaints up quarter-on-quarter: 6 in Q2 vs 2 in Q1",
          "Dignity observations show inconsistency between the stable day team and newer cover staff",
        ],
        gaps: ["Morning routine under-staffed relative to dependency at peak", "Newer staff not yet completed dignity-in-care refresher"],
        narrative: "An honest downgrade, not an exposure: the GM recorded Requires improvement himself and Cassi's assessment agrees.",
      },
      C2: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        dir: "down",
        evidence: [
          "Care plans current but preference-led detail thinning in records made by cover staff",
          "Two residents' stated routines not consistently followed on sampled days",
        ],
        gaps: ["Continuity of named carers broken by turnover"],
      },
      C5: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        dir: "down",
        evidence: [
          "Carer turnover 22% this quarter (group average 9%)",
          "Three exit interviews cite workload and burnout",
          "Supervisions slipping for the staff covering vacancies",
        ],
        gaps: ["No retention plan on file yet", "Supervision backlog for cover staff"],
      },
    },
    history: [
      { date: "10 Mar 2026", text: "Caring self-rated Good across its statements." },
      { date: "16 May 2026", text: "Caring statements C1, C2 and C5 self-rated Requires improvement — the GM flagged the slip himself, rooted in 22% carer turnover. Cassi agrees. Honest, but moving the wrong way." },
    ],
    strengths: ["GM recorded the decline honestly — zero divergence", "Governance (Well-led) is what caught it: his own reporting surfaced the problem"],
    redFlags: ["Carer turnover 22% this quarter", "Complaints up 6 vs 2 quarter-on-quarter", "Two dignity concerns from relatives", "No retention plan on file"],
  },

  {
    id: "willow",
    name: "Willow Grange",
    town: "Gosforth, Newcastle",
    gmName: "Helen Carr",
    rm: "Vacant — interim cover",
    beds: 36,
    overall: { label: "Requires improvement", rag: "amber", dir: "flat" },
    lastAssessed: "22 May 2026",
    kq: {
      Safe: { gm: "Requires improvement", cassi: "Requires improvement", dir: "flat", note: "Competency reassessments and body-map records outstanding — honestly recorded." },
      Effective: { gm: "Good", cassi: "Good", dir: "flat", note: "Holding." },
      Caring: { gm: "Good", cassi: "Good", dir: "flat", note: "Positive feedback despite pressures." },
      Responsive: { gm: "Requires improvement", cassi: "Requires improvement", dir: "flat", note: "Care-plan reviews behind schedule." },
      "Well-led": { gm: "Requires improvement", cassi: "Requires improvement", dir: "flat", note: "Registered manager vacancy; interim cover only." },
    },
    overrides: {
      S8: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        evidence: [
          "Medicines competency reassessments outstanding for 3 of 11 administering staff",
          "MAR audit otherwise clean; no administration errors recorded",
        ],
        gaps: ["Three competency reassessments overdue (due 30 April)"],
      },
      S3: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        evidence: [
          "Two body-map records incomplete following unwitnessed bruising in April",
          "Both incidents referred to safeguarding appropriately and on time",
        ],
        gaps: ["Body-map completion not yet reliable on night shift"],
      },
      R1: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        evidence: ["9 of 36 care-plan reviews behind schedule", "Reviews completed are good quality — the issue is volume, not standard"],
        gaps: ["Review backlog of 9, oldest dated 2 March"],
      },
      W2: {
        gm: "Requires improvement",
        cassi: "Requires improvement",
        evidence: [
          "Registered manager post vacant since January; interim cover two days a week",
          "Recruitment under way — second-round interviews scheduled",
          "Deputy holding day-to-day but without registration",
        ],
        gaps: ["No registered manager in post", "Interim cover insufficient for the audit cycle"],
      },
    },
    history: [
      { date: "22 May 2026", text: "Requires improvement recorded on Safe, Responsive and Well-led statements. The GM's ratings match Cassi's assessment throughout. Low ratings, low exposure — nothing is overstated, and the root cause (RM vacancy) is named." },
    ],
    strengths: ["Honest self-assessment under pressure — zero divergence", "Safeguarding referrals made properly even where records lag"],
    redFlags: ["Registered manager vacancy since January", "3 medicines competency reassessments overdue", "Care-plan review backlog of 9"],
  },
];

/* ---- build: expand every home to the full 34-statement assessment -------- */
function buildEstate() {
  return HOMES.map((h) => {
    const assessments = QS_CATALOGUE.map((qs) => {
      const o = (h.overrides && h.overrides[qs.id]) || {};
      return {
        id: qs.id,
        kq: qs.kq,
        title: qs.title,
        gm: o.gm || "Good",
        cassi: o.cassi || "Good",
        dir: o.dir || "flat",
        evidence: o.evidence || BASELINE_EVIDENCE[qs.id],
        gaps: o.gaps || [],
        narrative: o.narrative || null,
      };
    });

    const RATING_ORDER = { Inadequate: 0, "Requires improvement": 1, Good: 2, Outstanding: 3 };
    const divergences = assessments
      .filter((a) => RATING_ORDER[a.gm] > RATING_ORDER[a.cassi])
      .map((a) => ({ qs: a.id, title: a.title, kq: a.kq, gm: a.gm, cassi: a.cassi, why: (a.gaps || []).join("; ") }));

    const { overrides, gmName, ...rest } = h;
    return { ...rest, gm: gmName, assessments, divergences };
  });
}

const ESTATE = buildEstate();

const SCENARIOS = [
  "Where's my biggest exposure right now?",
  "Which homes are improving, and which are slipping?",
  "Walk me through Meadowbrook's journey since March.",
  "Where are GMs recording above Cassi's assessment?",
];

module.exports = { GROUP, ESTATE, SCENARIOS };
